# Generated by Django 5.1 on 2025-01-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piaro_app', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='is_like',
            field=models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], default=0),
            preserve_default=False,
        ),
    ]
