# Generated by Django 5.1 on 2025-02-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piaro_app', '0005_alter_collection_publications_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
